### ISSUE TITLE
[BUG] Network error, Network error ,Network error, Network error.

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [eternalUnion/AngryLevelLoader#10]
# Description
When downloading levels it always says "network error" which causes it to not download at all.

# Plugins Used
* PluginConfigurator 
* AngryLevelLoader 
* 

# Console Logs
none

# Extras
If you can make it so it continues the download after the network error that would help my problem.

**Comment by eternalUnion** [comment]
The error obviously states that download cannot be continued due to an issue so it is not possible to just continue the download process. Network error usually indicates angry being out of date, download url being invalid or having no internet connection. Could you provide a list of levels you encounter the error, or does it happen for all the levels?

**Comment by N0VA-The-Git-User** [comment]
it does happen for all the levels just excessively to the larger ones, i have been able to download smaller ones and angry is up to date. the levels are bloodbath palace and greybox skill test.

**Comment by eternalUnion** [comment]
Skilltest links seem to be valid. It could be an antivirus, google drive or unreliable internet connection related problem

**Comment by N0VA-The-Git-User** [comment]
my internet is equivalent to a Bluetooth potato so that's probably why
